"""Remote machine you can rsync to. RunPod or a box you already SSH into."""
from __future__ import annotations

from typing import Protocol


class Transport(Protocol):
    def ssh(self, remote_cmd: str) -> None: ...
    def rsync_up(self, local_dir: str, remote_dir: str) -> None: ...
    def rsync_down(self, remote_path: str, local_dir: str) -> None: ...
    def close(self) -> None: ...
